pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-hg
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Mercurial
  desc: Clones a mercurial repository
  type: clone
  image: plugins/drone-hg
  labels:
    - scm
    - vcs
    - hg
