workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-hg

pipeline:
  test:
    image: golang:1.9
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out

  build:
    image: golang:1.9
    commands: sh .drone.sh
    when:
      branch: master
      event: push

  publish_linux_amd64:
    image: plugins/docker
    group: tags
    repo: plugins/hg
    tags: [ "latest", "1.1", "1" ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
